{
 "title": "Arris dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Downstream Locked Channels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "Lock Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median Receive SNR",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "dBm",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "SNR/MER" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th % Receive SNR",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "dBm",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "SNR/MER" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Locked Channels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "Lock Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median Transmit Power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "dBm",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th % Transmit Power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "dBm",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "Channel [[tag_Channel ID]]",
     "groupBy": [
      { "params": [ "Channel ID" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "Channel [[tag_Channel ID]]",
     "groupBy": [
      { "params": [ "Channel ID" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "SNR/MER" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Corrected Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Corrected Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "downstream",
     "query": "SELECT derivative(last(\"Corrected\"), 10s) FROM \"downstream\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Corrected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Uncorrectable Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "downstream",
     "query": "SELECT derivative(last(\"Corrected\"), 10s) FROM \"downstream\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "Channel [[tag_Channel ID]]",
     "groupBy": [
      { "params": [ "Channel ID" ], "type": "tag" }
     ],
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Modem Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "startup",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Startup Procedure",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Procedure" ], "type": "tag" }
     ],
     "measurement": "startup",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Comment" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Bonded Channels",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Channel ID" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "Lock Status" ], "type": "field" }
      ],
      [
       { "params": [ "Modulation" ], "type": "field" }
      ],
      [
       { "params": [ "Frequency" ], "type": "field" }
      ],
      [
       { "params": [ "Power" ], "type": "field" }
      ],
      [
       { "params": [ "SNR/MER" ], "type": "field" }
      ],
      [
       { "params": [ "Corrected" ], "type": "field" }
      ],
      [
       { "params": [ "Uncorrectables" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Bonded Channels",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Channel" ], "type": "tag" },
      { "params": [ "Channel ID" ], "type": "tag" }
     ],
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "Lock Status" ], "type": "field" }
      ],
      [
       { "params": [ "US Channel Type" ], "type": "field" }
      ],
      [
       { "params": [ "Frequency" ], "type": "field" }
      ],
      [
       { "params": [ "Width" ], "type": "field" }
      ],
      [
       { "params": [ "Power" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}